<template>
    <div class="container">
      <div class="loading">
        <div class="centerScreen">
        <div class="content Timesroman">
            <h3 class="title"> Game Report</h3>   
            <h2 class="title">Introdcution:</h2>
            <p class="body">This section presents an  overall report of  Youngres gameplay by different groups. In total, <strong>{{GroupFilter.group_ids.length}}</strong> group (<span v-for="(group, i) in GroupFilter.group_ids" :key="i"><strong> {{group.group_id}}:</strong> {{group.description}}, </span>)  and played  <strong>{{result.length}}</strong> game and <strong>{{result[0].chapters.length}}</strong> chapters.  Below presents a summary of chapter regarding student provided decision-making during  gameplay. To properly understand student/group  performance for empathy, emotional recognition, relaxation, visualisation, breathing, active listening, Muslim culture, social skills, etc, we have labeled student decisions in several categories (i.e., positive, negative, complex, neutral, etc). Event questions, scenatios, and corresponding student decisions have been considered together for  labeling  a decsion.</p>

            <center>
              <div class="col-md-12">
                <p class="fig">Table 1: example of student decision labeling.</p>
                <table class="table table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">Event Question</th>
                            <th scope="col">Decision</th>
                            <th scope="col">Decision annotation</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>How is Ahmed feeling right now?</td>
                            <td> Sad </td>
                            <td>Positive (Suitable/correct decsion, refers to good perfromance of student/group. )</td>
                          </tr>
                          <tr>
                            <td>Should you argue with your mom?</td>
                            <td>Shout at her</td>
                            <td>Negative (Not expected/wrong decision, refers to lower performance of student/group.)</td>
                          </tr>
                          <tr>
                            <td>Are you a boy or a girl?</td>
                            <td>Boy</td>
                            <td>Neutral (Depends on the situation, could be suitable decsion, but definitely not refers to lower performance of student/group.)</td>
                          </tr>

                        </tbody>
                  </table>
               </div>
            </center>


            <p class="nb">[N.B. This report is auto-generated by following a specific template based on API data (might not be grammatically correct), and intended only to help teacher assessment.]</p>

            <p class="title">To generate report  select Chapter and Event (Multiple choice). For group comparision select any two group from the filter.</p>
            
            <div class="row">
                <div class=" col-md-2">
                    <select class="custom-select" v-model="game" @change="selectGame($event)">
                        <option v-for="(item, index) in result" :key="index" :value="item.gameCode">{{item.gameCode}} </option>
                    </select>
                </div>
                <div class="col-md-2">
                    <select class="custom-select" v-model="chapter"  @change="selectChapter($event)">
                        <option v-for="(item, index) in chapters" :key="index" :value="item">{{item}} </option>
                    </select>
                </div>
                <div class="col-md-3">
                    <select class="custom-select" @change="selectChoice($event)">
                        <option selected value="choice">Multiple-choice</option>
                        <option value="timed">Temporal</option>
                    </select>
                </div>
                <div class="col-md-5 mt-sm-3 mt-md-0">
                    <button class="btn btn-primary" @click="filter()">Filter</button>
                    <button class="btn btn-success" style="margin-left: 10px" @click="submitData(chapter)">Generate Analytics</button>
                    <button class="btn btn-dark" style="margin-left: 10px" @click="chapterInfo()">Chapter Info</button>
                </div>
            </div>

            <hr class='gap'>
            <h2 class="title">{{chapter_info[0].title}}</h2>
            <p><strong>Chapter Objective:</strong> {{chapter_info[0].des}}.</p>

            <div v-for="(data, index) in all_final_data" :key="index">
                <div v-if='index==0'>

                    <p class="body"><strong>Result: </strong>This chapter has played by group <span v-for="(group, l) in groupName" :key="l"><strong> {{group}}, </strong></span> the number of students in the group <strong>{{data.total_student}}</strong>, and  the total number of decisions made <strong>{{data.total_decision}}</strong>.

                    <br><strong><em>Table-{{index+2}}</em></strong> presents the sentiment score of individual events decisions, and <strong><em>Figure-{{index+1}}</em></strong> presents the overall emotional scores of all decisions from chapter {{data.eventid}}. The overall sentiment scores were: positive ({{data.total_sentiment_score[0]}}%), negative ({{data.total_sentiment_score[1]}} %), complex ({{data.total_sentiment_score[3]}}%), and neutral ({{data.total_sentiment_score[2]}}%). Here, <strong>{{data.total_sentiment_score[1]}}%  negative sentiment  representing ~{{data.total_sent_student_count[1]}} student  that might be in polarity risk </strong> <span v-if='data.total_decision < 10'>(though for this particular chapter number of decisions is small, only {{data.total_decision}}, which makes it tough to comment)</span>. In comparison, <strong>{{parseInt(data.total_sentiment_score[0], 10)+parseInt(data.total_sentiment_score[2], 10)}}%  s positive and neutral emotions, representing ~{{data.total_sent_student_count[0]+data.total_sent_student_count[2]}}  students, which seems normal</strong>. <br>

                      <strong class='red'>The most polarized decision has come from EventId (<span v-for="(sentiment, index) in data.sentiment_score" :key="index"><span v-if="sentiment.ne> 0">{{sentiment.event}}, </span></span>) and polarized decisions were: <span v-for="(sentiment, index) in data.sentiment_score" :key="index" ><span v-if="sentiment.ne>0"><span v-for="(s, index) in sentiment.sep_choice" :key="index">{{s.neg[0]}}</span>, </span></span></strong>.
                    </p><br>

                    <p class="fig">Table {{index+2}}: Group score on individual events of {{chapter_info[0].title.split(':').shift()}}.</p>
                    <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">EventId</th>
                                <th scope="col">Event Question</th>
                                <th scope="col">Decisions (decisions count)</th>
                                <th scope="col">Decsion Score (in total of 100%)</th>
                              </tr>
                            </thead>
                            <tbody  v-for="(sentiment, i) in data.sentiment_score" :key="i">
                              <tr>
                                <th scope="row">{{sentiment.event}}</th>
                                <td>{{sentiment.event_des}}</td>
                                <td> <li class="nostyle" v-for="(choice, j) in sentiment.choice" :key="j"> {{j+1}}. {{choice.c}} ({{choice.n}})</li></td>
                                <td>
                                    <span v-if="sentiment.po>0">Positive: {{sentiment.po.toFixed(1)}}<br></span>
                                    <span v-if="sentiment.ne>0">Negative: {{sentiment.ne.toFixed(1)}}<br></span>
                                    <span v-if="sentiment.com>0">Complex: {{sentiment.com.toFixed(1)}}<br></span>
                                    <span v-if="sentiment.nu>0">Neutral: {{sentiment.nu.toFixed(1)}}<br></span>
                                </td>
                              </tr>
                            </tbody>
                            <tbody class='bold'>
                              <tr>
                                  <td></td>
                                  <td>Total Event  Count: {{data.sentiment_score.length}}</td>
                                  <td>Total Decision made: {{data.total_decision}}</td>
                                  <td>Positive: {{data.total_sentiment_score[0]}}%, Neutral: {{data.total_sentiment_score[2]}}%, Negative: {{data.total_sentiment_score[1]}}%</td>
                              </tr>
                            </tbody>
                      </table>


                      <div class="row">
                          <div class="col-md-4">
                              <v-chart :options="barGraph[0]" width="100%"/>
                              <p class="fig">Fig. {{index+1}}: Sentiment score of total decision from chapter {{data.chapter_id}}.</p>
                         </div>
                          <div class="col-md-4" v-if='groupName.length==2' >
                               <v-chart :options="barGraph[1]" width="100%"/>
                               <p class="fig">Fig. {{index+2}}: Sentiment score of group {{groupName[0]}}.</p>
                          </div>
                          <div class="col-md-4" v-if='groupName.length==2'>
                               <v-chart :options="barGraph[2]" width="100%"/>
                               <p class="fig">Fig. {{index+3}}: Sentiment score of group {{groupName[1]}}.</p>
                          </div>
                       </div>

                        <div class="row" v-if='groupName.length==1'>
                          <div class="col-md-12">
                              <v-chart :options="lineGraph[0]" width="100%"/>
                              <p class="fig">Fig. {{index+2}}: Individual student score {{data.chapter_id}}.</p>
                         </div>
                       </div>

                 

                      <div class="row">
                          <div class="col-md-12 verdict">
                              <h6 class="fig">Final Verdict of  possible student  polarization: Chapter {{data.eventid}}, played by group <span v-for="(group, m) in groupName" :key="m"><strong> {{group}}, </strong></span>.</h6>
                              <table class="table table-bordered">
                                    <thead v-if='groupName.length==2'>
                                        <td rowspan="2"></td>
                                        <th colspan="2" scope="colgroup">Both group</th>
                                        <th colspan="2" scope="colgroup">Group: {{groupName[0]}}</th>
                                        <th colspan="2" scope="colgroup">Group: {{groupName[1]}}</th>
                                    </thead>
                                    <thead>  
                                        <th scope="col"></th>
                                        <th scope="col">Count</th>
                                        <th scope="col">Percentange</th>
                                        <th scope="col" v-if='groupName.length==2'>Count</th>
                                        <th scope="col" v-if='groupName.length==2'>Percentange</th>
                                        <th scope="col" v-if='groupName.length==2'>Count</th>
                                        <th scope="col" v-if='groupName.length==2'>Percentange</th>
                                    </thead>

                                    <tbody class='pol'>
                                        <td>Polarization risky student</td>
                                        <td>~ {{data.total_sent_student_count[1]}}</td>
                                        <td>~ {{Math.round((data.total_sent_student_count[1]/data.total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[1].total_sent_student_count[1]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[1].total_sent_student_count[1]/all_final_data[1].total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[2].total_sent_student_count[1]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[2].total_sent_student_count[1]/all_final_data[2].total_student)*100)}}%</td>
                                    </tbody>

                                    <tbody class='po'>
                                        <td>Positive student</td>
                                        <td>~ {{data.total_sent_student_count[0]}}</td>
                                        <td>~ {{Math.round((data.total_sent_student_count[0]/data.total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[1].total_sent_student_count[0]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[1].total_sent_student_count[0]/all_final_data[1].total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[2].total_sent_student_count[0]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[2].total_sent_student_count[0]/all_final_data[2].total_student)*100)}}%</td>
                                    </tbody>
                                    <tbody class='neu'>
                                        <td>Neutral student</td>
                                        <td>~ {{data.total_sent_student_count[2]}}</td>
                                        <td>~ {{Math.round((data.total_sent_student_count[2]/data.total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[1].total_sent_student_count[2]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[1].total_sent_student_count[2]/all_final_data[1].total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[2].total_sent_student_count[2]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[2].total_sent_student_count[2]/all_final_data[2].total_student)*100)}}%</td>
                                    </tbody>
                                    <tbody class='com'>
                                        <td>Complex  student</td>
                                        <td>~ {{data.total_sent_student_count[3]}}</td>
                                        <td>~ {{Math.round((data.total_sent_student_count[3]/data.total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[1].total_sent_student_count[3]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[1].total_sent_student_count[3]/all_final_data[1].total_student)*100)}}%</td>
                                        <td v-if='groupName.length==2'>~ {{all_final_data[2].total_sent_student_count[3]}}</td>
                                        <td v-if='groupName.length==2'>~ {{Math.round((all_final_data[2].total_sent_student_count[3]/all_final_data[2].total_student)*100)}}%</td>
                                    </tbody>
                                    <tbody class='tot'>
                                        <td>Total Student</td>
                                        <td>{{data.total_student}}</td>
                                        <td>100%</td>
                                        <td v-if='groupName.length==2'>{{all_final_data[1].total_student}}</td>
                                        <td v-if='groupName.length==2'>100%</td>
                                        <td v-if='groupName.length==2'>{{all_final_data[2].total_student}}</td>
                                        <td v-if='groupName.length==2'>100%</td>
                                    </tbody>
                            </table>
                      </div>
                  </div> <!-- v-if close -->
              </div> <!-- v-for for chapter  close--> 
       

              </div>
                <div class="row" style="padding: 20px 0">
                      <div class="col-4 text-center">
                          <button class="btn btn-primary" @click="home">Home</button>
                      </div>
                      <div class="col-4 text-right">
                          <button class="btn btn-primary export" @click="exportOpt">Export report as PDF</button>
                      </div>
                </div>
              </div>
          </div>
       </div>
     </div>
</template>

<script>

    import ECharts from 'vue-echarts'
    import 'echarts/lib/chart/bar'
    import 'echarts/lib/component/tooltip'
    import 'echarts-gl'
    import axios from "axios";
    import json from './data.json';
    import chapterJ from './chapter.json'; 

    export default {
        components: {
            'v-chart': ECharts
        },
        data: function(){
            return {
                choice: 'choice',
                n_decisions:0,
                total_student:0,
                total_students:[],
                individual_student_sentiment:[],
                decisions: [],
                max_choice: 0,
                distinct_event: [],
                distinct_event_temp: [],
                unique_decision_final:[],
                unique_decision_final_temp:[],
                type: null,
                game: null,
                version: null,
                chapter: null,
                barGraph: [],
                lineGraph:[],
                result: [],
                chapters: [],
                filterStudent: [],
                GroupFilter: [],
                getFilterHeader: null,
                choiceList: null,
                choiceList_name: null,
                groupName:[],
                label: json,
                chapter_json:chapterJ,
                chapter_info:[],
                d_count:[],
                new_score:[],
                all_final_data:[],
                d_c:[],
            }
        },
        mounted(){

          this.game = 1;
          this.version = 1;
          this.chapter=1593;

          const requestOne = axios.get("descriptions/games");
          const requestTwo = axios.get("filters/group");
          const requestThree = axios.get("filters/student");

          axios.get('descriptions/games')
              .then(res => {
                this.$store.state.games = JSON.parse(res.request.response).games;
                this.loading = false;
                this.loadData();
                // this.submitData();
              });
          axios.all([requestOne, requestTwo, requestThree ]).then(axios.spread((...responses) => {
            this.$store.state.games = responses[0].data.games;
            this.GroupFilter = responses[1].data
            this.filterStudent = responses[2].data
            this.groupsList = this.GroupFilter.group_ids;
            this.SelectGroupOne = this.$route.params.groupOne;
            this.SelectGroupTwo = this.$route.params.groupTwo;
            this.loadData();

          })).catch(errors => {
            console.log(errors);
          })

          this.$root.$on('loadFilterHeaderSingle', (Filter) => { 
            this.getFilterHeader = {};
            if(Filter.group !== null && Filter.group !== undefined) {
              if(Filter.student === null )
                delete  Filter.student;

              this.getFilterHeader = Filter;

            } else if(Filter.student !== null && Filter.student !== undefined) {

              if(Filter.group === null )
                delete  Filter.group;
              this.getFilterHeader = Filter;
            }

            this.submitData(this.chapter);
          });
          this.submitData(this.chapter);
        }
        ,
        methods: {

            exportOpt(){
                window.print();
            },
            home(){
                this.$router.push('/main');
            },

           chapterInfo(){
            this.$root.$emit('viewChapterInfo', {
              game: this.game,
              version: this.version,
              chapter: this.chapter
            });
            this.$modal.show("chapter_info");
             },

            filter(){

              this.$root.$emit('loadFilterDate', [this.GroupFilter, this.filterStudent, "single"]);
              this.$modal.show('filter');

            },
            selectGame(event){
                this.game = event.target.value;
                this.loadData();
            },
            selectChoice(event){
                this.choice = event.target.value;

            },
            selectChapter(event){
                this.chapter = event.target.value;

            },
            loadData(){
                let key = this.game;
                this.result = this.$store.state.games;

                let res = this.result.filter(
                    function(data){
                        if(data.gameCode === key.toString())
                            return data
                    }
                );
                if(res.length > 0){
                    res = res[0];
                    this.chapters = res.chapters;
                    this.version = res.gameVersion;
                }
            },
 
 
            submitData(item){
                this.loading = true;
                this.chapterData(item);
                if(this.getFilterHeader !== null && JSON.stringify(this.getFilterHeader) !== JSON.stringify({})) {
                  axios.get("decision?gameCode=" + this.game + "&gameVersion=" + this.version + "&chapterCode=" + item, {headers: {filters: JSON.stringify(this.getFilterHeader)}}).then(res => {
                    this.decisions = res.data.decisions;
                    this.makeZero();
                    this.studentCounts();
                    this.groupCount();
                    if(this.decisions.length>0){   
                            this.dataAnalysis(this.decisions);
                            this.d_counts(item);}

                    if(this.groupName.length==2 && this.decisions.length>0){
                            this.groupName.forEach(groupId => {
                                let group = this.decisions.filter(decisions  => decisions.student.group_code == groupId);
                                this.dataAnalysis(group);
                                this.d_counts(item);
                            });       
                    }

                    if(this.decisions.length>0 && this.groupName.length==1){                
                          this.eachStudentScore(item);
                          this.lineGraphs(this.individual_student_sentiment);   
                    }

                  });


                }else {
                  axios.get("decision?gameCode=" + this.game + "&gameVersion=" + this.version + "&chapterCode=" + item).then(res => {
                    this.decisions = res.data.decisions;
                    this.makeZero();
                    this.studentCounts();
                    this.groupCount();
                    if(this.decisions.length>0){
                          this.dataAnalysis(this.decisions);
                          this.d_counts(item);
                          if(this.groupName.length==1){                
                            this.eachStudentScore(item);
                            this.lineGraphs(this.individual_student_sentiment);   
                          }                  
                     }

                  });
                }
            },

            makeZero(){ //make some variable empty array

                    this.all_final_data=[];
                    this.individual_student_sentiment=[];
                    this.barGraph=[];
                    this.lineGraph=[];

            },

            studentCounts(){ //student count
                    let counts = {};
                    this.decisions.forEach(decision => counts[decision.student.student_code] = 1  + (counts[decision.student.student_code] || 0));
                    this.total_student=Object.keys(counts).length;
                    this.total_students=Object.keys(counts);
            },

            eachStudentScore(item){ //easch student sentiment score
                    this.total_students.forEach(name => {
                    let student_data = this.decisions.filter(decisions  => decisions.student.student_code == name);
                    this.dataAnalysis(student_data);
                    this.d_counts(item);
                    });
                  },
            groupCount(){ //group count
                    this.groupName=[];
                    try{ 
                      this.getFilterHeader.group.forEach((m) =>{this.groupName.push(m.min_value)});
                    }
                    catch{
                      this.GroupFilter.group_ids.forEach((m) =>{this.groupName.push(m.group_id)});
                    }
            },

            chapterData(item){ // rturn chapter deatils

              this.chapter_info = this.chapter_json.filter(el  => el.chpater == item);

            },

            dataAnalysis(decisions){
                this.distinct_event_temp = [];
                this.unique_decision_final_temp = [];
                this.unique_decision_final = [];
                var eventList = [];
                var choice = [];

                decisions.forEach(value => {

                  if(value.eventType === 'timed'){
                    this.unique_decision_final_temp.push([value.eventCode, value.choice, value.eventDescription]);
                    let t = 0;
                    for( ; t < this.distinct_event_temp.length; t++){
                      if(this.distinct_event_temp[t].value === value.eventCode){
                        break;
                      }
                    }
                  if(this.distinct_event_temp.length === t)
                      this.distinct_event_temp.push({value: value.eventCode, description: value.eventDescription});

                  }else{
                    let i=0;
                    for (; i < eventList.length; i++){


                      if(eventList[i].value === value.eventCode) {
                        eventList[i].count++;
                        break;
                      }
                    }
                    if(i === eventList.length)
                      eventList.push({value: value.eventCode, count: 1, description: value.eventDescription});


                    let p = 0;
                    for (; p < choice.length; p++){
                      if(choice[p].value === value.choice)
                        break;
                    }
                    if(p === choice.length)
                      choice.push({value: value.choice, choice: []});

                  }

                });

              choice.forEach(value => {
                eventList.forEach(value1 => {
                  value.choice.push({
                    value: 0,
                    name: value.value,
                    count: 0,
                    event: value1.value,
                    description: value1.description
                  });
                });

              });


              decisions.forEach(value => {
                if(value.eventType !== 'timed'){
                  choice.forEach(value1 => {
                    let x = 0;
                    for(; x < value1.choice.length; x++){
                      if(value1.choice[x].event === value.eventCode && value1.choice[x].name === value.choice)
                        value1.choice[x].count++;

                    }

                  });
                }

              });
              choice.forEach(value1 => {

                value1.choice.forEach(value2 => {

                  let m =0;
                  for(; m < eventList.length; m++){
                    if(eventList[m].value === value2.event){
                      value2.value = (value2.count/eventList[m].count)*100;
                    }
                  }

                });

              });
              this.unique_decision_final = choice;
              this.choiceList = eventList;
            },
            d_counts(item){
                  this.unique_decision_final.forEach(( message) =>{   
                     message.choice.forEach(( new_m) =>{
                        if (new_m.value > 0) {
                            this.d_count.push(new_m);
                          }      
                    });

                  });

                  this.d_count.sort((a, b) => a.event - b.event);
                  this.n_decisions=0;
                  var total_answer=0;
                  var tps=0, tnes=0, tcoms=0, tnus=0; //variable to save total postitive negative complex and neutral student
                  var tpo=0, tne=0, tnu=0,tcom=0; // variable to save total postitive negative complex and neutral score
                  this.d_count.forEach((m) =>{total_answer+=m.count; });
                  this.d_count.forEach((m) =>{
                              var po=0, ne=0, nu=0, com=0;
                              const pos=[], neg =[], compl=[], nut=[];

                              this.label.forEach((el) =>{ //calculation of positive negative and neutral
                                if(el.e == m.event){ 
                                  el.Choices.forEach( (choice)=> {
                                    if(choice[0] == m.name && choice[1] == 'pos' ){po=(m.count/total_answer)*100; tpo+=po; pos.push(m.name);}
                                    if(choice[0] == m.name && choice[1] == 'neg' ){ne=(m.count/total_answer)*100; tne+=ne;neg.push(m.name);}
                                    if(choice[0] == m.name && choice[1] == 'neu'){nu=(m.count/total_answer)*100; tnu+=nu;nut.push(m.name);}
                                    if(choice[0] == m.name && choice[1] == 'com'){com=(m.count/total_answer)*100;tcom+=com;compl.push(m.name);}
                                   });
                                 }
                              });
                              

                              const record = this.new_score.find(element => element.event == m.event);

                              if (record) {
                                  record.po += po;
                                  record.ne += ne;
                                  record.nu += nu;
                                  record.com += com;
                                  record.choice.push({c:m.name,n:m.count});
                                  record.sep_choice.push({pos:pos,neg:neg,compl:compl, nut:nut});
                              } else {
                                  this.new_score.push({
                                      event: m.event,
                                      event_des: m.description,
                                      po:po,
                                      ne:ne,
                                      nu:nu,
                                      com:com,
                                      choice:[{c:m.name,n:m.count}],
                                      sep_choice:[{pos:pos,neg:neg,compl:compl, nut:nut}]
                                  });     
                              }
                
                          });

                  tps=Math.round((this.total_student)* (tpo/ 100)); //calculation of total postive student count
                  tnes=Math.round((this.total_student)* (tne/ 100));
                  tnus=Math.round((this.total_student)* (tnu/ 100));
                  tcoms=Math.round((this.total_student)* (tcom/ 100));


                  this.n_decisions+=total_answer;
                  this.all_final_data.push({chapter_id:item,total_student:this.total_student, total_decision:total_answer, sentiment_score:this.new_score, total_sentiment_score: [Math.round(tpo),Math.round(tne),Math.round(tnu),Math.round(tcom)], total_sent_student_count:[tps, tnes,tnus,tcoms] });
                  this.individual_student_sentiment.push([Math.round(tpo),Math.round(tne),Math.round(tnu),Math.round(tcom)]);
                  this.barChartTotalScore(tpo,tne,tnu,tcom);
                  this.total_score=[];
                  this.new_score=[];
                  this.unique_decision_final=[];
                  this.d_count=[];  

            },


            barChartTotalScore(tpo,tne,tnu,tcom){ //bar chart for total emotional score
                this.barGraph.push( {
                                 grid: {
                                      left: '3%',
                                      right: '4%',
                                      bottom: '3%',
                                      containLabel: true
                                  },

                                xAxis: {
                                    type: 'category',
                                    data: ['Positive', 'Negative', 'Complex','Neutral']
                                },
                                yAxis: {
                                    type: 'value'
                                },
                                series: [{
                                    data: [Math.round(tpo),Math.round(tne), Math.round(tcom), Math.round(tnu)],
                                    label:{show: true, formatter: '~{c}%', fontSize: 12, rotate:90,verticalAlign: 'middle',
                                    position: 'insideBottom',distance: 20},
                                    type: 'bar'
                                }]});

            },

            lineGraphs(data){ //bar chart for total emotional score
                let series1=[], series2=[], series3=[], series4=[];
                data.slice(1).forEach((score) =>{series1.push(score[0]); series2.push(score[1]);series3.push(score[2]);series4.push(score[3]);});
                this.lineGraph.push( {
       
                                tooltip: {
                                    trigger: 'axis'
                                },
                                legend: {
                                    data: ['Positive', 'Negative', 'Neutral', 'Complex']
                                },
                                grid: {
                                    left: '3%',
                                    right: '4%',
                                    bottom: '3%',
                                    containLabel: true
                                },
         
                                xAxis: {
                                    type: 'category',
                                    boundaryGap: false,
                                    data: this.total_students,
                                    axisLabel: { rotate: 90 },

                                },
                                yAxis: {
                                    type: 'value'
                                },
                                series: [
                                    {
                                        name: 'Positive',
                                        type: 'line',
                                        data: series1
                                    },
                                    {
                                        name: 'Negative',
                                        type: 'line',
                                        data: series2
                                    },
                                    {
                                        name: 'Neutral',
                                        type: 'line',
                                        data: series3
                                    },
                                    {
                                        name: 'Complex',
                                        type: 'line',
                                        data: series4
                                    },
                             
                                ]

                              });

            },

        }
    }
</script>

<style scoped lang="scss">
    .title{
      font-weight: bold;
      font-size: 18px;
      color: #e35219;

    }
    .sub-title{
      color: #e35219;
      margin: 26px 0 6px;
    }
    .btn-success, .btn-dark{
        padding: 4px 19px;
        border: 0;
    }
    .btn-primary{
        padding: 4px 19px;
        background: #e35219;
        border: 0;
    }
    .custom-select{
        text-transform: capitalize;
        font-weight: bold;
    }
    .content{
        margin: 50px 0;
    .custom-control{
        margin-top: 16px;
    }
    }
    .eventlist{
        list-style: none;
        padding: 0;
        li {
            padding: 1px 10px;
            background: #325973;
            color: white;
            border: 1px solid white;
            cursor: pointer;
        }
        li:hover{
            background: #848484;
        }
    }
    
    .echarts {width: 100% !important;height: 300px!important; }



    h2.title[data-v-16f032e2] {
    font-family: serif;
    font-size: 22px;
    font-weight: bold;
    }

    h3.title {
    text-align: center;
    font-family: serif;
    color: black!important;
    font-size: 29px!important;
    padding-bottom: 26px;
    }

    p.body {
    font-family: serif;
    font-size: 17px;
    text-align: justify;
    }

    .table th, .table td {
    padding: 2px 5px 2px 10px;
    vertical-align: top;
    }

    tbody {
    font-size: 15px;
    font-family: serif;
    }

    p.fig {
    font-family: serif;
    font-style: italic;
    text-align: center;
    font-weight: bold;
   }

   li.nostyle {
    list-style: none;
  }


  p.nb[data-v-16f032e2] {
      font-size: 12px;
      font-family: serif;
      font-style: italic;
      font-weight: bold;
      color: #c52121;
  }
  .col-md-6.verdict {
    padding-top: 10px;
    height: 272px;
    margin-top: 53px;
    border-radius: 7px;
}

  .th {
    font-family: serif;
  }

  .gap{border-bottom: 1px solid #FFF;
    background-color: #DADADA;
    height: 2px;
    margin: 20px 0px 20px;
    }

    .verdict td {
    font-weight: bold;
}

tbody.pol {
    

    tbody.pol {
    background: #f10000d9;
    color: white;
}
}

tbody.po, tbody.neu  {
    background: #008000b5;
}

tbody.com {
    background: #f52f2fad;
}

tbody.np {
    background: #0000ffad;
    color: white;
}

.col-md-6.verdict h6 {
    color: #ea0000;
    font-size: 19px;
    font-family: serif;
    font-weight: bold;
}

tbody.pol {
    background: red;
    color: white;
}

.bold {
    font-weight: bold;

}
</style>